#to acceot user input use-input()

name=input("Enter your name:")
print(type(name))
print("hello " + name)
print(f"hello {name}")
print("hello {}" .format(name))
age=int(input("how old are you:"))
print(type(age))
age1=eval(input("how old are you:"))
print(type(age1))